site_name: "Подготовка к интервью"
site_url: "http://saba-interview.ru/"


nav:
  - "Главная": index.md
  - "СА":
      - "БД":
          - "Ключи": sa/db/keys.md
          - "Нормализация": sa/db/normalization.md
          - "Индексы": sa/db/indexes.md
          - "SQL":
              - "Базовые конструкции": sa/db/sql/basics.md
              - "Джойны": sa/db/sql/joins.md
              - "Агрегации": sa/db/sql/aggregations.md
              - "Вопросы на собеседованиях": sa/db/sql/interview-questions.md
      - "Интеграции":
          - "Способы интеграций": sa/integrations/integration-methods.md
          - "RabbitMQ vs Kafka": sa/integrations/rabbitmq-vs-kafka.md
          - "REST": sa/integrations/rest.md
          - "SOAP": sa/integrations/soap.md
          - "REST vs SOAP": sa/integrations/rest-vs-soap.md
      - "Форматы данных":
          - "JSON vs XML": sa/data-formats/json-vs-xml.md
          - "JSON Schema": sa/data-formats/json-schema.md
          - "XSD": sa/data-formats/xsd.md
      - "Взаимодействие":
          - "Оркестрация и хореография": sa/interaction/orchestration-vs-choreography.md
          - "Синх. и асинх. взаим-ие": sa/interaction/sync-vs-async.md
      - "Аутентификация и авторизация": sa/authentication-and-authorization.md
      - "Идентификация": sa/identification.md
      - "Виды архитектур": sa/architecture-types.md
      - "Идемпотентность": sa/idempotence.md
      - "Монолит vs микросервис": sa/monolith-vs-microservices.md
      - "HTTP": sa/http.md
  - "БА":
      - "Виды требований": ba/requirement-types.md
      - "Use case и User story": ba/use-case-and-user-story.md
      - "Методологии": ba/methodologies.md
      - "UML": ba/uml.md
      - "BPMN": ba/bpmn.md
      - "Роли в команде": ba/team.md

theme:
  name: material
  language: ru

site_author: "Aleksandr Petrov"
copyright: "Aleksandr Petrov, ptrvAleks, 2025"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
