site_name: "Подготовка к интервью"
site_url: "http://saba-interview.ru/"
site_description: "Помощь СА/БА аналитикам в подготовке к собеседованиям"

nav:
  - "Главная": index.md
  - "СА":
      - "БД":
          - "Ключи": sa/db/keys.md
          - "Нормализация": sa/db/normalization.md
          - "Индексы": sa/db/indexes.md
          - "SQL":
              - "Базовые конструкции": sa/db/sql/basics.md
              - "Джойны": sa/db/sql/joins.md
              - "Агрегации": sa/db/sql/aggregations.md
              - "Вопросы на собеседованиях": sa/db/sql/interview-questions.md
      - "Интеграции":
          - "Способы интеграций": sa/integrations/integration-methods.md
          - "RabbitMQ vs Kafka": sa/integrations/rabbitmq-vs-kafka.md
          - "REST": sa/integrations/rest.md
          - "SOAP": sa/integrations/soap.md
          - "REST vs SOAP": sa/integrations/rest-vs-soap.md
      - "Форматы данных":
          - "JSON vs XML": sa/data-formats/json-vs-xml.md
          - "JSON Schema": sa/data-formats/json-schema.md
          - "XSD": sa/data-formats/xsd.md
      - "Взаимодействие":
          - "Оркестрация и хореография": sa/interaction/orchestration-vs-choreography.md
          - "Синх. и асинх. взаим-ие": sa/interaction/sync-vs-async.md
      - "Аутентификация и авторизация": sa/authentication-and-authorization.md
      - "Идентификация": sa/identification.md
      - "Виды архитектур": sa/architecture-types.md
      - "Идемпотентность": sa/idempotence.md
      - "Монолит vs микросервис": sa/monolith-vs-microservices.md
      - "HTTP": sa/http.md
  - "БА":
      - "Виды требований": ba/requirement-types.md
      - "Use case и User story": ba/use-case-and-user-story.md
      - "Методологии": ba/methodologies.md
      - "UML": ba/uml.md
      - "BPMN": ba/bpmn.md
      - "Роли в команде": ba/team.md

theme:
  name: material
  language: ru

plugins:
  - search
  - rss:
      # адрес выходного RSS (будет создан в site/)
      feed_url: /feed.xml
      # сколько последних записей включать
      limit: 20
      # простая маска: включить все страницы (регекс)
      match_path: ".*"

site_author: "Alexander Petrov"
copyright: "Alexander Petrov, petrvAlex, 2025"
repo_url: https://github.com/petrvAlex/SABAinterview
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences

extra:
    consent:
      title: Файлы cookie
      description: Мы используем файлы cookie, чтобы распознавать ваши повторные посещения и предпочтения, а также оценивать эффективность нашей документации и то, находят ли пользователи то, что ищут. С вашего согласия вы помогаете нам сделать документацию лучше.
    analytics:
      provider: google
      property: G-CYRYFTSVH4
      feedback:
        title: Эта страница была полезна?
        ratings:
          - name: 'Да'
            icon: material/thumb-up-outline
            value: 1
            note: >-
              Thanks for your feedback!
          - name: 'Нет'
            icon: material/thumb-down-outline
            value: 0
            note: >-
              Спасибо за отзыв! Помогите улучшить эту страницу используя <a href="https://github.com/petrvAlex/SABAinterview/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.