site_name: Подготовка к интервью
site_url: https://ptrvaleks.github.io/
nav:
  - Главная: index.md
  - СА:
      - БД:
          - Ключи: sa/БД/Ключи.md
          - Нормализация: sa/БД/Нормализация.md
          - Индексы: sa/БД/Индексы.md
          - SQL:
             - Базовые конструкции: sa/БД/SQL/Базовые конструкции.md
             - Джойны: sa/БД/SQL/Джойны.md
             - Агрегации: sa/БД/SQL/Агрегации.md
             - Вопросы на собеседованиях: sa/БД/SQL/Вопросы на собесе.md
      - Интеграции:
          - Способы интеграций: sa/Интеграции/Способы интеграций.md
          - RabbitMQ vs Kafka: sa/Интеграции/RabbitMQ vs Kafka.md
          - REST: sa/Интеграции/REST.md
          - SOAP: sa/Интеграции/SOAP.md
          - REST vs SOAP: sa/Интеграции/REST vs SOAP.md
      - Форматы данных:
          - JSON vs XML: sa/Форматы данных/JSON vs XML.md
          - JSON Schema: sa/Форматы данных/JSON Schema.md
          - XSD: sa/Форматы данных/XSD.md
      - Взаимодействие:
          - Оркестрация и хореография: sa/Взаимодействие/Оркестрация vs хореография.md
          - Синх. и асинх. взаим-ие: sa/Взаимодействие/Синхронное и асинхронное взаимодействие.md
      - Аутентификация и авторизация: sa/Аутентификация и авторизация.md
      - Виды архитектур: sa/Виды архитектур.md
      - Идемпотентность: sa/Идемпотентность.md
      - Монолит vs микросервис: sa/Монолитная vs микросервисная.md
      - HTTP: sa/http.md
  - БА:
      - Главная: ba/index.md
      - Виды требований: ba/Виды требований.md
      - Use case и User story: ba/Use case и User story.md
      - Методологии: ba/Методологии.md
      - UML: ba/UML.md
      - BPMN: ba/BPMN.md
theme:
  name: material
site_author: Aleksandr Petrov
copyright: Aleksandr Petrov, ptrvAleks, 2025
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences