site_name: Мои заметки
site_url: https://ptrvaleks.github.io/SABAinterview/
nav:
  - Главная: index.md
  - СА:
      - Главная: sa/index.md
      - БД:
          - Главная: sa/bd/index.md
      - Аутентификация и авторизация: sa/Аутентификация и авторизация.md
  - БА:
      - Главная: ba/index.md
theme:
  name: material